FROM node:17.3.0-alpine3.14

WORKDIR /app/source

RUN corepack enable
ADD . .
RUN yarn
RUN cd packages/business && \
    yarn build:production

WORKDIR /app/source/packages/site

CMD ["yarn", "build-serve"]
