let lng_en = {
	'index_slogan': 'Creation and dissemination are redefined by us.',
	'index_slogan_bottom': 'Publish what you love \u2000 Support what you love \u2000 Spread what you love',
	'go_publish': 'Publish',
	'go_buy': 'Buy',
	'please_install_metamask': 'Please install metamask first!',
	'please_set_polygon': 'Please switch to the Polygon main network',
	'error_no_erc20': 'The address you provided is not an erc20 token, please re-enter it',
	'pulish_success': 'Congratulations on your successful release',
	'you_gain_nft': 'The NFT you got is',
	'show_detail': 'View details',
	'art_info': 'Publish',
	'art_name': 'Work Name',
	'fit_rate': 'Percentage of Earnings',
	'fit_rate_tip': 'When your item is shared and profited by others, what percentage of the profits you want from the share of the profits',
	'access_coin': 'Payment Currency',
	'access_coin_tip': 'Please select the payment currency of your support (enter token symbol or address)',
	'please_input_coin': 'enter token symbol or address',
	'price': 'Selling Price',
	'max_share': 'Maximum Number of Shares',
	'max_share_tip': 'How many times do you want each user to help you spread?',
	'art_desc': 'Work Description',
	'art_desc_tip': 'Please describe your work in simple words. Accurate and effective description can help other users to understand your work more accurately.',
	'pic_cover': 'Cover Photo',
	'pic_cover_tip': 'Please upload your cover image in the area below \nCover files support these formats: JPEG/JPG/PNG',
	'upload_file_tip1': 'To upload a file, please click or drag the file here.',
	'upload_file_tip2': 'To upload the cover, please click or drag the cover file here.',
	'art_file': 'Work File',
	'art_file_tip': 'Please upload your work file in the area below',
	'submit': 'submit',
	'publish_open': 'Open Source publish',
	'publish_encry': 'Encryption　publish',
	'have_submit': 'uploaded information?',
	'up_file': 'Upload Item file',
	'cancel': 'Cancel',
	'go_upload': 'To Upload',
	'inpt_NFT_ID': 'Enter NFT ID',
	'inpt_NFT_ID_tip': 'Please fill in the NFT ID of the content you want to bind in the area below',
	'no_NFT_owner': 'You are not the owner of this NFT',
	'index': 'Home',
	'collection': 'Collection',
	'publish': 'Publish',
	'introPublish': 'Publish Instructions',
	'choose_encryPublish':'Choose encrypted release, only users who have purchased the NFT work are allowed to view the content of the work.',
	'choose_openPublish':'Users can download and view the content of the work regardless of whether the work is purchased or not by default. Turn on to require payments upon access.',
	'introPublish1': 'Before you publish your work, you need to know the following information,which will help you understand the complete publishing process:',
	'introPublish2': 'You can choose between open source release and encrypted release.\n Choose encrypted release, only users who have purchased the NFT work are allowed to view the content of the work;\n Choose open source release, users can download and view the content of the work regardless of whether the work is purchased or not.',
	'introPublish3': ' After the user purchases your work, he will have the right to sell a certain amount of the work for second time, and you will take a draw from his total income.',
	'introPublish4': 'After your work is published to the blockchain, all information is open and transparent, all rights are protected by the blockchain, and the SparkLink platform has no right to interfere. At the same time, the platform will collect  2% handling fee as operational support.',
	'introPublish5': 'When your NFT work is creating, you can choose whether to support secondary creation. If you choose allowed support it, users will be allowed to make secondary creation on your work and sell it in the original system, you will get a proportional dividend from the sale proceeds of your subordinate users.',
	'index_slogan3': 'Used by whole world,\nCreate NFT, Share your content',
	'index_slogan4': 'SparkLink has the most unique and moneyback model \nof any decentralized platform.\n\nAnd the users are allowed to create and share them NFT items,\ngain revenue through sales and sharing.',
	'index_miniBox_1': '197+\nCountries user',
	'index_miniBox_2': 'N+\nToken  support',
	'index_miniBox_3': '99% MAX \n  Share moneyback',
	'index_message_1': 'We are so different from others',
	'index_message_2': 'Everyone is allowed to create and share content in the form of NFT, generating revenue in perpetuity through node sales and distribution.',
	'index_message_3': 'No need middlemen, spread becomes so simple',
	'index_message_4': 'Free to use,  No registration, No hassle',
	'index_message_5': 'Quickly publish and share your NFT content items just by connecting your wallet.',
	'index_message_6': 'Start in seconds.',
	'index_message_7': 'Connect your crypto wallet to start using the SparkLink in seconds.No registration needed,free to use.',
	'index_message_8': 'Learn how to start',
	'index_message_9': 'Join the community,Grab the rewards',
	'index_message_10': 'Learn how to start',
	'learn': 'Learn',
	'share': 'SHARE',
	'connect_wallet': 'Connect Wallet',
	'social_media': 'Socila Media',
	'market': 'Market',
	'resources': 'Resources',
	'save': 'save',
	'您已经连接MathWallet,当前账户： ': 'You have connected MathWallet ,account:  ',
	'您已经连接tokenpocket,当前账户： ': 'You have connected tokenpocket ,account:  ',
	'您已经连接metamask,当前账户： ': 'You have connected metamask ,account:  ',
	'请先连接钱包': 'Please connect your Wallet first!',
	'请先安装metamask': 'Please install metamask first!',
	'请切换至Polygon 主网络': 'Please select Plolygon Main-Net',
	'暂时无法获取到该nft的相关描述': 'The relevant description of the nft is not available for the time being.',
	'查看': 'View',
	'暂无可展示NFT': 'There is no NFT to display for the time being.',
	'您的签名有误,请查看签名账号是否正确': 'Your signature is incorrect. Please check whether the signature account is correct.',
	'参数错误': 'Parameter error',
	'您并不拥有此nft': 'You do not own this nft',
	'此nft还未生成': 'This nft has not been generated yet',
	'请求文件加密密钥失败': 'Failed to request file encryption key',
	'敬请期待': 'Comming Soon',
	'购买': 'Buy',
	'授权合约': 'Authorization contract',
	'回到首页': 'return Homepage',
	'创作者分红比例：': 'Proportion of dividend paid by creators: ',
	'售价：': 'Price:',
	'当前拥有者：': 'Current owner:',
	'当前拥有的子节点数量：': 'Number of child nodes currently owned:',
	'NFT是否加密：': 'Whether NFT is encrypted:',
	'未知': 'unknown',
	'是': 'yes',
	'否': 'not',
	'错误：服务器未响应': 'error: Server Have No Response',
	'获取nft子节点情况页面失败：': 'Failed to get NFT child node situation page',
	'正在解密文件': 'Decrypting files',
	'返回信息页面': 'Return to the information page',
	'正在下载文件': 'Downloading files',
	'回到我的收藏馆': 'Go back to my collection.',
	'目前收益：': 'Current earnings:',
	'领收益': 'Receive income',
	'售卖': 'Sell',
	'分红比例：': 'Dividend ratio:',
	'下载': 'Downaload',
	'分享链接复制成功': 'Sharing link copied successfully',
	'链接分享': 'Link sharing',
	'海报分享': 'Poster sharing',
	'所有人可通过分享链接或海报进入作品详情页查看以及购买本作品': 'Everyone can view and purchase this work by sharing links or posters to the details page of the work.',
	'点火价格: ': 'Sprak Price:',
	'最大分享次数：': 'Maximum number of shares:',
	'剩余分享次数：': 'Remaining number of shares:',
	'加密作品': 'Encrypted works',
	'开源作品': 'Open source works',
	'此NFT的子节点已经售完,我们给您推荐了其他还能购买的节点：': 'The child nodes of this NFT have been sold out,and we recommend other nodes that can be purchased:',
	'已经成功授权买方': 'Has successfully authorized the buyer',
	'请将下方链接分享给买方,': 'Please share the link below with the buyer, ',
	'买方会进入此链接来购买这个NFT': 'The buyer will go to this link to purchase the NFT',
	'返回': 'return',
	'买方钱包地址 *': 'Buyer’s wallet address *',
	'取消': 'cancel',
	'你有信息尚未填写': 'You have some information that you haven’t filled in yet.',
	'已经成功发布作品': 'The work has been successfully published.',
	'交易已提交,当前网络较拥堵,请稍等后去我的收藏中查看': 'The transaction has been submitted. The current network is congested. Please check it in my collection later.',
	'作品基本信息已提交成功': 'The basic information of the work has been submitted successfully.',
	'账户发生变化,请切换回原账户': 'The account has changed,please switch back to the original account',
	'铸造': 'mint',
	'解决出版困境，源自ERC21支持': 'An ERC721 Token Trying to Solve Existing Publishing Dilemma',
	'打包并上传': 'Pack and Upload',
	'填写售卖信息':'Fill in the sales information',
	'是否允许二次创作':'Allow secondary creation',
	'是否允许商用':'Allow commercial use',
	'售卖价格':'Sell Price',
	'作品权限':'Work Permission',
	'允许一级节点免费铸造':'First-class nodes are allowed to be cast free of charge.',
	'请在下方区域填写你希望售卖的价格，以及售卖对象的钱包地址。':'Please fill in the price you want to sell \n and the wallet address of the person you want to sell in the area below.',
	'加密发布':'Paywall',
	'正在发布您的作品...请在钱包中处理请求...':'Your work is being published.\n nPlease process the request in your wallet.',
	'您正在为该NFT补充信息：':'You are providing additional information for this NFT: ',
	'似乎遇到了些小问题：':'There seems to be some minor problem: ',
	'获取NFT信息出错':'Error getting NFT information',
	'上传文件失败...不用担心，稍后可在[我的收藏]页面查看NFT并重新上传，失败原因：':'Failed to upload file. Do not worry. You can view the NFT later on the [Collectons] page and upload it again. Reason for failure:',
	'正在上传文件中...':'Uploading file',
	'请求加密密钥失败':'Failed to request encryption key',
	'读取文件出错！':'Error reading file!',
	'未知错误 ！':'Unknown error',
	'上传文件到服务器中...':'Upload files to the IPFS server.',
	'更新文件信息失败...不用担心，稍后可在[我的收藏]页面查看NFT并重新上传，失败原因：':'Failed to update file information. Do not worry. You can view the NFT later on the [Collection] page and upload it again. Reason for failure:',
	'正在更新NFT信息..':'Updating NFT information..',
	'作品基本信息已提交成功....等待签名..':'The basic information of the work has been submitted successfully. Waiting for an autograph..',
	'作品基本信息已提交成功....当前网络较拥堵...':'The basic information of the work has been submitted successfully. At present, the network is more congested.',
	'正在打包文件...':'The file is being packaged.',
	'文件打包失败，请重试':'Failed to package the file. Please try again.',
	'稍安勿躁，马上就好':'It will be ready in a minute.',
	'好像出现了点小问题':'There seems to be a little problem.',
	'最大长度为300个字符':'The maximum length is 300 characters',
	'正在创建NFT...请在钱包中确认您的请求..':'Creating NFT... Please confirm your request in your wallet..',
	'文件过大！上传的文件不能超过100MB':'The file is too large! Uploaded files cannot exceed 100MB',
	'Untitled':'Untitled',
	'no_upload_file':'The NFT has been created, but the information has not been populated and the file has not been uploaded',
	'去上传':'upload',
	'请先连接钱包，否则只能查看和下载开源文件':'Please connect your wallet first, otherwise you can only view and download open source files',
	'请切换至':'Please switch to',
	'链并查看此NFT':'chain and view this NFT',
	'请先连接正确的链，否则可能无法查看此NFT':'Please connect the correct chain first, otherwise you may not be able to view this NFT',
	'CONTACT US':'CONTACT US',
	'needHelp':'Need Help?',
	'poster_loading': 'loading the poster...',
	'tree_loading':'loading the node tree',
	'保存':'save',
	'copy_email_address_success': 'Copy EMail Address Success',
	'copy_email_address_error': 'Copy EMail Address Success',
	'铸造后节点价格为：': 'Minted Node Price:',
	'铸造此节点后的节点可售价格': 'mined node price',
	'owner': 'Owner',
	'profit': 'Profit',
	'show_node_tree':'Node Tree Display',
}
export default lng_en;
