let lng_en={
	'index_slogan': 'Spreads and supports each other,\n Like a spark that will link and light up the world.',
	'index_slogan_bottom': 'Publish what you love \u2000 Support what you love \u2000 Spread what you love',
	'go_publish': 'Go Publish',
	'go_buy': 'Go Buy',
	'please_install_metamask': 'Please install metamask first!',
	'please_set_polygon': 'Please switch to the Polygon main network',
	'error_no_erc20': 'The address you provided is not an erc20 token,please re-enter it',
	'pulish_success': 'Congratulations on your successful release',
	'you_gain_nft': 'The NFT you got is',
	'show_detail': 'View details',
	'art_info': 'Create item information',
	'art_name': 'Item name',
	'fit_rate': 'Percentage of earnings',
	'fit_rate_tip': 'When your item is shared and profited by others,what percentage of the profits you want from the share of the profits',
	'access_coin': 'Payment currency',
	'access_coin_tip': 'Please select the payment currency of your support (enter token symbol or address)',
	'please_input_coin': 'enter token symbol or address',
	'price': 'Selling price',
	'max_share': 'Maximum number of shares',
	'max_share_tip': 'How many times do you want each user to help you spread?',
	'art_desc': 'Item describe',
	'art_desc_tip': 'Please describe your work in simple words. Accurate and effective description can help other users to understand your work more accurately.',
	'pic_cover': 'Cover picture',
	'pic_cover_tip': 'Please upload your cover image in the area below \nCover files support these formats: JPEG/JPG/PNG',
	'upload_file_tip1': 'To upload a file,please click or drag the file here.',
	'upload_file_tip2': 'Only single file upload is supported,and multiple types of files are supported.',
	'art_file': 'Item file',
	'art_file_tip': 'Please upload your work file in the area below',
	'submit': 'submit',
	'publish_open': 'Open Source publish',
	'publish_encry': 'Encryption　publish',
	'have_submit': 'uploaded information?',
	'up_file': 'Upload Item file',
	'cancel': 'Cancel',
	'go_upload': 'To Upload',
	'inpt_NFT_ID': 'Enter NFT ID',
	'inpt_NFT_ID_tip': 'Please fill in the NFT ID of the content you want to bind in the area below',
	'no_NFT_owner': 'You are not the owner of this NFT',
	'index': 'Home',
	'collection': 'Collection',
	'publish': 'Publish',
	'introPublish': 'Publish instructions',
	'introPublish1': 'Before you publish your work,you need to know the following information,which will help you understand the complete publishing process:',
	'introPublish2': 'Your work will be stored in IPFS (InterPlanetary FileSystem),and the storage address will be recorded on Ethernet Square,bound to your NFT.',
	'introPublish3': 'You can choose to save your work open source on IPFS or encrypt it on IPFS. Encrypted works can only be accessed by readers who hold your published NFT.',
	'introPublish4': 'If you choose to encrypt and save on IPFS,you need to set the address of the work after uploading the basic information of the work to the chain. We will guide you to complete this process,do not worry.',
	'introPublish5': 'When you publish your work on our platform,we default that you will support secondary creation,and readers in your promotional network have the right to replace their NFT address with their own secondary creation.',
	'index_slogan3': 'Used by whole world,\nCreate NFT,Share your content',
	'index_slogan4': 'SparkLink has the most unique and moneyback model \nof any decentralized platform.\n\nAnd the users are allowed to create and share them NFT items,\ngain revenue through sales and sharing.',
	'index_miniBox_1': '197+\nCountries user',
	'index_miniBox_2': 'N+\nToken  support',
	'index_miniBox_3': '99% MAX \n  Share moneyback',
	'index_message_1': 'Free to use\nNo registration,no hassle',
	'index_message_2': 'Quickly publish and share your NFT items just by connecting your wallet.',
	'index_message_3': 'Earn passive income with ',
	'index_message_4': 'CREAT & SHARE',
	'index_message_5': '\nShare content,get revenue',
	'index_message_6': 'Start in seconds.',
	'index_message_7': 'Connect your crypto wallet to start using the SparkLink in seconds.No registration needed,free to use.',
	'index_message_8': 'Learn how to start',
	'index_message_9': 'Join the community,Grab the rewards',
	'index_message_10': 'Learn how to start',
	'learn': 'Learn',
	'share': 'SHARE',
	'connect_wallet': 'Connect Wallet',
	'social_media': 'Socila Media',
	'market': 'Market',
	'resources': 'Resources',
	'您已经连接MathWallet,当前账户： ':'You have connected MathWallet ,account:  ',
	'您已经连接tokenpocket,当前账户： ':'You have connected tokenpocket ,account:  ',
	'您已经连接metamask,当前账户： ':'You have connected metamask ,account:  ',
	'请先连接钱包':'Please connect your Wallet first!',
	'请先安装metamask':'Please install metamask first!',
	'请切换至Polygon 主网络':'Please select Plolygon Main-Net',
	'暂时无法获取到该nft的相关描述':'The relevant description of the nft is not available for the time being.',
	'查看':'View',
	'暂无可展示NFT':'There is no NFT to display for the time being.',
	'您的签名有误,请查看签名账号是否正确':'Your signature is incorrect. Please check whether the signature account is correct.',
	'参数错误':'Parameter error',
	'您并不拥有此nft':'You do not own this nft',
	'此nft还未生成':'This nft has not been generated yet',
	'请求文件加密密钥失败':'Failed to request file encryption key',
	'敬请期待':'Comming Soon',
	'购买':'Buy',
	'授权合约':'Authorization contract',
	'回到首页':'return Homepage',
	'创作者分红比例：':'Proportion of dividend paid by creators',
	'售价：':'Price:',
	'当前拥有者：':'Current owner:',
	'当前拥有的子节点数量：':'Number of child nodes currently owned:',
	'NFT是否加密：':'Whether NFT is encrypted:',
	'未知':'unknown',
	'是':'yes',
	'否':'not',
	'错误：服务器未响应':'error: Server Have No Response',
	'获取nft子节点情况页面失败：':'Failed to get NFT child node situation page',
	'正在解密文件':'Decrypting files',
	'返回信息页面':'Return to the information page',
	'正在下载文件':'Downloading files',
	'回到我的收藏馆':'Go back to my collection.',
	'目前收益：':'Current earnings:',
	'领收益':'Receive income',
	'售卖':'Sell',
	'分红比例：':'Dividend ratio:',
	'下载':'Downaload',
	'分享链接复制成功':'Sharing link copied successfully',
	'链接分享':'Link \u2000 \u2000sharing',
	'海报分享':'Poster sharing',
	'所有人可通过分享链接或海报进入作品详情页查看以及购买本作品':'Everyone can view and purchase this work by sharing links or posters to the details page of the work.',
	'点火价格: ':'Sprak Price:',
	'最大分享次数：':'Maximum number of shares:',
	'剩余分享次数：':'Remaining number of shares:',
	'加密作品':'Encrypted works',
	'开源作品':'Open source works',
	'此NFT的子节点已经售完,我们给您推荐了其他还能购买的节点：':'The child nodes of this NFT have been sold out,and we recommend other nodes that can be purchased:',
	'已经成功授权买方':'Has successfully authorized the buyer',
	'请将下方链接分享给买方,':'Please share the link below with the buyer,',
	'买方会进入此链接来购买这个NFT':'The buyer will go to this link to purchase the NFT',
	'返回':'return',
	'请在下方区域填写你希望售卖的价格,以及售卖对象的钱包地址。':'Please fill in the price you want to sell and the wallet address of the person you want to sell in the area below.',
	'买方钱包地址 *':'Buyer’s wallet address *',
	'取消':'cancel',
	'你有信息尚未填写':'You have some information that you haven’t filled in yet.',
	'已经成功发布作品':'The work has been successfully published.',
	'交易已提交,当前网络较拥堵,请稍等后去我的收藏中查看':'The transaction has been submitted. The current network is congested. Please check it in my collection later.',
	'似乎遇到了些小问题：':'There seems to be some minor problem:',
	'作品基本信息已提交成功':'The basic information of the work has been submitted successfully.',
	'账户发生变化,请切换回原账户':'The account has changed,please switch back to the original account',
	'铸造':'cast',
	'解决出版困境，源自ERC21支持':'An ERC721 Token Trying to Solve Existing Publishing Dilemma',
	'打包并上传':'Pack and Upload'
}
export default lng_en;